all: myprime intermediate prime1 prime2 prime3
myprime:
	gcc -o myprime myprime.c list.c -lm
intermediate:
	gcc -o intermediate intermediate.c list.c
prime1:
	gcc -o prime1 prime1.c list.c
prime2:
	gcc -o prime2 prime2.c list.c
prime3:
	gcc -o prime3 prime3.c list.c
clean:
	rm myprime intermediate prime1 prime2 prime3 myfifo1 myfifo2 myfifo3
